
services:
  zabbix-db:
    image: mysql:5.7
    container_name: zabbix-db
    environment:
      MYSQL_ROOT_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    volumes:
      - zabbix-db-data:/var/lib/mysql
    networks:
      - zabbix_network

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_DB: zabbix
    depends_on:
      - zabbix-db
    ports:
      - "10051:10051"
    networks:
      - zabbix_network

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-frontend
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-db
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_DB: zabbix
      PHP_TZ: "Europe/Paris"
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server
    networks:
      - zabbix_network

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
    networks:
      - zabbix_network

networks:
  zabbix_network:
    driver: bridge

volumes:
  zabbix-db-data:
    driver: local
